version: '3.5'

networks:
 localdev:
  name: localdev

services:
  main-api:
   build:
    context: ./
    dockerfile: ./ELRDServerAPI/Dockerfile
   restart: always
   ports:
    - "7000:5000"
   depends_on:
    - db-server
   networks:
    - localdev

  db-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: db-server
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=NESRK903!RULEZ
     - MSSQL_TCP_PORT=1433
    ports:
     - "1400:1433"
    networks:
     - localdev